Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = "node-control"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.auto_update = false
end
