# Use the official Redis image as a base
FROM redis:latest

# You can add further configurations here if needed.
# For example, to copy a custom redis.conf file:
# COPY redis.conf /usr/local/etc/redis/redis.conf
# CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# Expose the default Redis port (6379)
EXPOSE 6379