Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "jenkins"
  # Configura a interface de rede em modo bridge
  config.vm.network "public_network", bridge: "Intel(R) Ethernet Connection (13) I219-LM"  # Substitua pelo nome da sua interface de rede física
  config.vm.network "private_network", ip:"192.168.1.5"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3064"
    # Adicione outras configurações do VirtualBox aqui, se necessário
  end

  # config.vm.provision 'shell', path: "provision.sh"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 6379, host: 6379
end
