spring:
  application:
    name: learningkotlin
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver
    username: renan
    password:
    url: jdbc:h2:mem:accounttestdb
  jpa:
    hibernate:
      ddl-auto: create
#H2 settings